### ISSUE TITLE
please don't

### ISSUE THREAD

**Issue by medecau** [pawamoy-insiders/.github#1]
hey @pawamoy

invitation to a github org is something i take carefully, so when i received the invitation for this i postponed it so i could pay attention to what was happening and almost reported this to github as spam. you need to better communicate what this invite is about. i was not expecting it and had little context awaiting me on arrival.

this feels a lot like i am going down some sales funnel and i don't like that. i already sponsor you for mkdocstrings which is the project i am interested in. if in the future i am interested in other projects of yours i'll consider bumping up the sponsorship but please don't add me to insiders orgs that's not why i'm here or what i want from the sponsorship.

**Comment by pawamoy** [comment]
Hi @medecau, thank you for the feedback.

First thing, just to reassure you: if you're getting invited, it's because that is a benefit of the sponsorship tier you selected. It is not a way to try and get more money from you! With the tier you selected, you get access to the "Insiders" program, which takes the form of a GitHub organization with private forks of my projects, containing more features. This is explained in several places, listed below.

---

Getting access to Insiders is listed as a benefit of the tier(s) you selected, on my GitHub Sponsors page. For example:

![tier-10](https://github.com/user-attachments/assets/0d44b8e5-32b9-454b-8506-b5fa5ab1fdd3)

Creating a sponsorship with one of those tiers will also display the following text, as well as sending it by email (at least it's supposed to be):

> You will shortly receive an invitation to join my @pawamoy-insiders organization on GitHub, giving you access to all my Insiders repositories. It can take up to 30 minutes: if you're in a hurry, don't hesitate to drop me a message on Gitter/Matrix/Telegram (`@pawamoy`) or an email at insiders@pawamoy.fr, and I will accelerate the process :wink: 

...or

> You will shortly receive an invitation to join my @pawamoy-insiders organization on GitHub, giving you access to all my Insiders repositories.

...depending on the tiers. Have you seen such text or received such email? How would you recommend we make it more clear what and why the @pawamoy-insiders organization is? Maybe something like "**What is this**? See details here: https://pawamoy.github.io/insiders"?

Before accepting the invitation, if you look at the org page, you can see this:

> This organization contains all my [Insiders](https://pawamoy.github.io/insiders/) projects. [Learn what Insiders is](https://pawamoy.github.io/insiders/#what-is-insiders), or how to gain access by [becoming a sponsor](https://pawamoy.github.io/insiders/#how-to-become-a-sponsor).

...which I think is enough, since it links to all the relevant information? Once you're a member, the org readme changes a bit, but still has all the relevant links.

You mention that your interest in sponsoring me is for mkdocstrings: thank you so much! Note that to use the Insiders features of mkdocstrings-python (for example https://mkdocstrings.github.io/python/usage/configuration/general/#show_inheritance_diagram), you *must* accept the invitation to the @pawamoy-insiders organization, to get access to the private fork of the Python handler, which you can install from there :slightly_smiling_face: 

Now it is totally fine if you're not interested in any Insiders feature of projects, and just do not want to join the organization.

With that said, I actually don't know how it looks from the invited user's perspective when they decline the invitation. Have you kept being invited over and over and had to decline each time? If that's the case, then that is a terrible user experience indeed, and I'm sorry for that. Some users don't notice the invitation (there is no GitHub notification for it), and therefore my automated system just resends it after it failed (I think it fails after 7 days). I'm not sure what happens when a user declines, and I guess I was hoping GitHub would just not send the invitation. I will update the automated invitation system to allow these two things:

- excluding sponsors who are not interested in joining the org
- if an invitation failed, don't resend it. Interested sponsors can always contact me again so that they start getting the invitation again.

I can then immediately add you to the exclude list, to make sure you never receive the invitation again. Would that work for you?

**Comment by pawamoy** [comment]
The automated invitation system is now updated as described above :slightly_smiling_face: You've been added to the exclusion list: let me know if you want to change that in the future!

**Comment by medecau** [comment]
thank you
